; Auto-generated. Do not edit!


(cl:in-package action_exp-msg)


;//! \htmlinclude AddFeedback.msg.html

(cl:defclass <AddFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:float
    :initform 0.0))
)

(cl:defclass AddFeedback (<AddFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_exp-msg:<AddFeedback> is deprecated: use action_exp-msg:AddFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <AddFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exp-msg:feedback-val is deprecated.  Use action_exp-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddFeedback>) ostream)
  "Serializes a message object of type '<AddFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddFeedback>) istream)
  "Deserializes a message object of type '<AddFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'feedback) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddFeedback>)))
  "Returns string type for a message object of type '<AddFeedback>"
  "action_exp/AddFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddFeedback)))
  "Returns string type for a message object of type 'AddFeedback"
  "action_exp/AddFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddFeedback>)))
  "Returns md5sum for a message object of type '<AddFeedback>"
  "52e771980e4e7329489ec918c554d012")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddFeedback)))
  "Returns md5sum for a message object of type 'AddFeedback"
  "52e771980e4e7329489ec918c554d012")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddFeedback>)))
  "Returns full string definition for message of type '<AddFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddFeedback)))
  "Returns full string definition for message of type 'AddFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AddFeedback
    (cl:cons ':feedback (feedback msg))
))
