; Auto-generated. Do not edit!


(cl:in-package action_exp-msg)


;//! \htmlinclude AddGoal.msg.html

(cl:defclass <AddGoal> (roslisp-msg-protocol:ros-message)
  ((target
    :reader target
    :initarg :target
    :type cl:integer
    :initform 0))
)

(cl:defclass AddGoal (<AddGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AddGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AddGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_exp-msg:<AddGoal> is deprecated: use action_exp-msg:AddGoal instead.")))

(cl:ensure-generic-function 'target-val :lambda-list '(m))
(cl:defmethod target-val ((m <AddGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_exp-msg:target-val is deprecated.  Use action_exp-msg:target instead.")
  (target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AddGoal>) ostream)
  "Serializes a message object of type '<AddGoal>"
  (cl:let* ((signed (cl:slot-value msg 'target)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AddGoal>) istream)
  "Deserializes a message object of type '<AddGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AddGoal>)))
  "Returns string type for a message object of type '<AddGoal>"
  "action_exp/AddGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AddGoal)))
  "Returns string type for a message object of type 'AddGoal"
  "action_exp/AddGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AddGoal>)))
  "Returns md5sum for a message object of type '<AddGoal>"
  "f9e0e2644ef8436bb1313201f33658ce")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AddGoal)))
  "Returns md5sum for a message object of type 'AddGoal"
  "f9e0e2644ef8436bb1313201f33658ce")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AddGoal>)))
  "Returns full string definition for message of type '<AddGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AddGoal)))
  "Returns full string definition for message of type 'AddGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AddGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AddGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AddGoal
    (cl:cons ':target (target msg))
))
