// Generated by gencpp from file action_exp/AddFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_EXP_MESSAGE_ADDFEEDBACK_H
#define ACTION_EXP_MESSAGE_ADDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_exp
{
template <class ContainerAllocator>
struct AddFeedback_
{
  typedef AddFeedback_<ContainerAllocator> Type;

  AddFeedback_()
    : feedback(0.0)  {
    }
  AddFeedback_(const ContainerAllocator& _alloc)
    : feedback(0.0)  {
  (void)_alloc;
    }



   typedef double _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::action_exp::AddFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_exp::AddFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AddFeedback_

typedef ::action_exp::AddFeedback_<std::allocator<void> > AddFeedback;

typedef boost::shared_ptr< ::action_exp::AddFeedback > AddFeedbackPtr;
typedef boost::shared_ptr< ::action_exp::AddFeedback const> AddFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_exp::AddFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_exp::AddFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_exp::AddFeedback_<ContainerAllocator1> & lhs, const ::action_exp::AddFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_exp::AddFeedback_<ContainerAllocator1> & lhs, const ::action_exp::AddFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_exp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_exp::AddFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_exp::AddFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exp::AddFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exp::AddFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exp::AddFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exp::AddFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_exp::AddFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52e771980e4e7329489ec918c554d012";
  }

  static const char* value(const ::action_exp::AddFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52e771980e4e7329ULL;
  static const uint64_t static_value2 = 0x489ec918c554d012ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_exp::AddFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_exp/AddFeedback";
  }

  static const char* value(const ::action_exp::AddFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_exp::AddFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 feedback\n"
;
  }

  static const char* value(const ::action_exp::AddFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_exp::AddFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_exp::AddFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_exp::AddFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<double>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_EXP_MESSAGE_ADDFEEDBACK_H
