// Generated by gencpp from file action_exp/AddGoal.msg
// DO NOT EDIT!


#ifndef ACTION_EXP_MESSAGE_ADDGOAL_H
#define ACTION_EXP_MESSAGE_ADDGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_exp
{
template <class ContainerAllocator>
struct AddGoal_
{
  typedef AddGoal_<ContainerAllocator> Type;

  AddGoal_()
    : target(0)  {
    }
  AddGoal_(const ContainerAllocator& _alloc)
    : target(0)  {
  (void)_alloc;
    }



   typedef int32_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::action_exp::AddGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_exp::AddGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AddGoal_

typedef ::action_exp::AddGoal_<std::allocator<void> > AddGoal;

typedef boost::shared_ptr< ::action_exp::AddGoal > AddGoalPtr;
typedef boost::shared_ptr< ::action_exp::AddGoal const> AddGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_exp::AddGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_exp::AddGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_exp::AddGoal_<ContainerAllocator1> & lhs, const ::action_exp::AddGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_exp::AddGoal_<ContainerAllocator1> & lhs, const ::action_exp::AddGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_exp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_exp::AddGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_exp::AddGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exp::AddGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_exp::AddGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exp::AddGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_exp::AddGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_exp::AddGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9e0e2644ef8436bb1313201f33658ce";
  }

  static const char* value(const ::action_exp::AddGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9e0e2644ef8436bULL;
  static const uint64_t static_value2 = 0xb1313201f33658ceULL;
};

template<class ContainerAllocator>
struct DataType< ::action_exp::AddGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_exp/AddGoal";
  }

  static const char* value(const ::action_exp::AddGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_exp::AddGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 target\n"
;
  }

  static const char* value(const ::action_exp::AddGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_exp::AddGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_exp::AddGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_exp::AddGoal_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_EXP_MESSAGE_ADDGOAL_H
